### ISSUE TITLE
[DOC] `Anatomy of an AAR file` is not up-to-date

### ISSUE THREAD

**Issue by alexcohn** [google/prefab#101]
**URL**
https://developer.android.com/studio/projects/android-library#aar-contents 

**Problem**
Unfortunately, https://developer.android.com/studio/projects/android-library#aar-contents is misleading. A typical prefab AAR contains **prefab** folder that is not listed in the doc, but does not include **classes.jar** or other entries that are listed as mandatory there.

The only entry in the AAR that Gradle Android Plugin requires to use it as a dependency, is **`/AndroidManifest.xml`**.

**Comment by DanAlbert** [comment]
Refiled against dac: https://issuetracker.google.com/157921087
