### ISSUE TITLE
[PKG] libjpeg-turbo

### ISSUE THREAD

**Issue by bk138** [google/prefab#111]
**Package name**
libjpeg-turbo

**Package URL**
https://libjpeg-turbo.org/

**Package source location**
https://github.com/libjpeg-turbo/libjpeg-turbo

**Comment by leleliu008** [comment]
This package had been publish to my maven repository hosted on github https://github.com/leleliu008/ndk-pkg-prefab-aar-maven-repo

You’re welcome to give it a try.
