### ISSUE TITLE
[FR] Java sources?

### ISSUE THREAD

**Issue by Zingam** [google/prefab#113]
If a C++ library contains some Java sources for glueing to Android, e.g. SDL2 implements its own SDLActivity instead of using NativeActivity?
Is such scenario foreseen?

We may want the java code precompiled or made available to be compiled or inherited.

**Comment by DanAlbert** [comment]
Java Code goes in an AAR, not the prefab package.

**Comment by alexcohn** [comment]
You can have compiled Java in the same AAR as the prefab native code, but the AGP (Android Gradle Plugin, the (only?) officially supported build tool) that recognizes both Java and native dependencies, cannot use the same dependency for both.
