### ISSUE TITLE
[DOC] Add example that uses the native library provided by ndk-samples/prefab/prefab-publishing

### ISSUE THREAD

**Issue by Consti10** [google/prefab#115]
I cannot figure out how to link to the native library after adding a module that contains native code bundled with prefab.
For example, if I use Jitpack to publish my library and then add it to another project as an module:
`implementation "com.github.Consti10.LiveVideo10ms:TelemetryCore:25f87dc9"`

I cannot find the native library in my CMakeLists.txt file.
Example:
`find_package(TelemetryReceiver REQUIRED CONFIG)`

I tried many different name strings but since there is no example that actually uses the native library from
prefab-publishing](https://github.com/android/ndk-samples/tree/master/prefab/prefab-publishing)

I do not have a starting point. Obvously, the "curl-ssl" example shows how to link to the native library of a module but both curl and ssl use the 'ndk-ports' approach and no the 'prefab-publishing via gradle / android studio" approach.

Sorry for the non-expertly descriptions, but I hope you can understand me anyways.

**Comment by Consti10** [comment]
When I look into the generated .aar I see a prefab.json file that looks like this:
`{
  "name": "TelemetryCore",
  "schema_version": 1,
  "dependencies": []
}`
But TelemetryCore is also not recognized 
aka 
`find_package(TelemetryCore REQUIRED CONFIG)`

**Comment by Consti10** [comment]
[TelemetryCore-unspecified.zip](https://github.com/google/prefab/files/5203808/TelemetryCore-unspecified.zip)

**Comment by Consti10** [comment]
Hello,
I forked the prefab example and added an example project (from the Android studio 'example native activity)
I call it prefab-dependency (prefab-publishing creates a usefull native library and publishes it via prefab, prefab-dependency shall include this generated library)
[Fork of ndk-samples / prefab](https://github.com/Consti10/ndk-samples/tree/master/prefab)

What do I need to link to the native library provided by prefab-publishing ?
I imported the generated .aar into the prefab-dependency example - linking it in gradle works:
[build.gradle file](https://github.com/Consti10/ndk-samples/blob/master/prefab/prefab-dependency/app/build.gradle)
`implementation project(path: ':mylibrary-debug')`

But I cannot find the native library inside the CMakeLists.txt file:
[CMakeLists.txt](https://github.com/Consti10/ndk-samples/blob/master/prefab/prefab-dependency/app/src/main/cpp/CMakeLists.txt)
`find_package(mylibrary REQUIRED CONFIG)`

**Comment by Consti10** [comment]
It throws the following build error:
`CMake Error at C:\Users\geier\Desktop\FPV_VR\PrefabTest\ndk-samples\prefab\prefab-dependency\app\src\main\cpp\CMakeLists.txt:14 (find_package):
  Could not find a package configuration file provided by "mylibrary" with
  any of the following names:

    mylibraryConfig.cmake
    mylibrary-config.cmake

  Add the installation prefix of "mylibrary" to CMAKE_PREFIX_PATH or set
  "mylibrary_DIR" to a directory containing one of the above files.  If
  "mylibrary" provides a separate development package or SDK, be sure it has
  been installed.`

**Comment by Consti10** [comment]
If you want I can create a pull request for the example, it might save you some time

**Comment by Consti10** [comment]
I can find the 'curl' library inside my example CMakeLists.txt without problems, but not the 'mylibrary' from prefab-publishing example.

**Comment by Consti10** [comment]
Hold on, there must be something wrong with my prefab-dependency example.
I just added 'mylibrary' to the curl-ssl example and there it seems to work. Let me check.

**Comment by Consti10** [comment]
Okay, I have added 'mylibrary' to the curl-ssl example and modified the example to update the UI element with a std::string returned from 'mylibrary'
[code](https://github.com/Consti10/ndk-samples/tree/master/prefab/curl-ssl)

It seems to be working now, but I'l make sure later.

**Comment by Consti10** [comment]
The issue was as simple as that I forgot to enable prefab inside the prefab-dependency project.
E.g.
`buildFeatures {
        viewBinding = true
        prefab = true
    }`

**Comment by Consti10** [comment]
I am sure this is mentioned somewhere, but for example here
https://developer.android.com/studio/build/native-dependencies?buildsystem=cmake
The information that prefab has to be manually enabled is missing.

**Comment by Consti10** [comment]
Closing this issue. If anybody has the samer error messages, here are some tipps:
a) Check if prefab was enabled (both in the publishing and dependency modules)
b) The name string for find_package is the module name

**Comment by DanAlbert** [comment]
Sorry about the missing portion of the docs! I've just sent the fix for that.

**Comment by DanAlbert** [comment]
It's in this doc: https://github.com/google/prefab/issues/115#issuecomment-691330962
