### ISSUE TITLE
[FR]prefabPublishing multiple header directories for one library

### ISSUE THREAD

**Issue by Consti10** [google/prefab#117]
It would be great if you could specify multiple header directories for one prefab library. Example:
```
prefab {
        TelemetryReceiver {
            headers "src/main/cpp/TelemetryReceiver"
            headers "src/main/cpp/SharedCppC"
        }
}
```

**Comment by DanAlbert** [comment]
That's an Android Gradle feature. Please file the big against the Android Gradle Plugin.

**Comment by Consti10** [comment]
Hello,
Unfortunately I don't think I have permissons to file bugs agains the android gradle plugin.
Aka Android Public Tracker > App Development > Android Studio > Gradle > Android Gradle Plugin > Prefab Integration
Therefore I filed the bug here:
Android Public Tracker > App Development > Android Studio 
https://issuetracker.google.com/issues/168775349

**Comment by DanAlbert** [comment]
Yeah, that's expected. Everything gets filed at the top level and goes through a common triage process.

I've moved it into the correct component and assigned it to myself since I'll probably be the one that fixes it.

**Comment by doggycoder** [comment]
en...,the same question, any update on this issue?

**Comment by DanAlbert** [comment]
No. Locking to try to help guide people to the correct bug: https://issuetracker.google.com/issues/168775349. Comment there, not here.
