### ISSUE TITLE
[BUG] CMake plugin generate invalid target name for header only package

### ISSUE THREAD

**Issue by brunotl** [google/prefab#122]
with CMP00037 ON ( default ) error is : 
```
  The target name "boost_config::boost_config" is reserved or not valid for
  certain CMake features, such as generator expressions, and may result in
  undefined behavior.
``` 

with  cmake_policy(SET CMP0037 OLD) error is :
```
  add_library Invalid name for INTERFACE library target:
  boost_config::boost_config
```

**Comment by DanAlbert** [comment]
https://cmake.org/cmake/help/latest/policy/CMP0037.html

> As a special case, ALIAS and IMPORTED targets may contain two consecutive colons.

Since header only libraries have no library to import, they don't use `IMPORTED` targets. Sounds like we need to create those targets with a different name like `boost_config_boost_config_headers` an `ALIAS` target to export the scoped name.

**Comment by brunotl** [comment]
CMake documentation is not  clear about that, but looking  cmake code it seem's, `INTERFACE` can be `IMPORTED`

see Ligne 235 and 251 of cmAddLibraryCommand.cxx :

https://github.com/Kitware/CMake/blob/d6ee9b4a43210553b8f4d3a11413f744e2affb26/Source/cmAddLibraryCommand.cxx#L235
https://github.com/Kitware/CMake/blob/d6ee9b4a43210553b8f4d3a11413f744e2affb26/Source/cmAddLibraryCommand.cxx#L251

**Comment by DanAlbert** [comment]
Good find. An `IMPORTED` target that doesn't actually import anything seems odd to me so I hadn't thought to try that. Seems to work though!

**Comment by DanAlbert** [comment]
Fix is merged. I'll start turning it into a release tomorrow.

**Comment by brunotl** [comment]
> Fix is merged. I'll start turning it into a release tomorrow.

thanks.

**Comment by brunotl** [comment]
The CMake policy documentation about double colon in target name :
https://cmake.org/cmake/help/latest/policy/CMP0028.html

**Comment by DanAlbert** [comment]
https://github.com/google/prefab/releases/tag/v1.1.2. If you're using AGP you can set `android.prefabVersion=1.1.2` in your gradle.properties (I've pushed the change to update the default as well). Otherwise use it however you have been :)
