### ISSUE TITLE
[BUG]Add example that uses the native library provided by ndk-samples/prefab/prefab-publishing in the same project

### ISSUE THREAD

**Issue by zhudongdong007** [google/prefab#130]
I already checked the site:https://github.com/google/prefab/issues/115
I got useful infomation from it. but still met some problems.

I hava two projects. 
NativeAAR(build error)
NativeAAR_NEW(works well)
https://github.com/zhudongdong007/NativeAARProject

You can compare the code of the two projects
The only difference between the two projects is NativeAAR(have the source code of mylibrary), but NativeAAR_NEW(without source code of mylibrary, but with the mylibrary-debug.aar)

I don't know why NativeAAR project have the build error, can you check it?

**Comment by DanAlbert** [comment]
This is an AGP issue, not a prefab issue. The only thing prefab does is generate build scripts.

AGP cannot do this: https://issuetracker.google.com/120166563
