### ISSUE TITLE
Stale prefab artifacts being packaged into AAR

### ISSUE THREAD

**Issue by nplez1** [google/prefab#139]
We are using prefab to package a native-only library in a submodule of our project that is then referenced as a dependency of our main application. We have found that the first build works fine but subsequent builds don't because, even though any changes get compiled into new shared object files, those shared object files aren't being packaged into the AAR. Instead, the stale asset is used and the new changes aren't reflected in the build.

Currently, we are using a workaround where we automatically delete the `build/intermediates/prefab_package` directory in a Gradle preBuild step. This seems to fix the problem, but shouldn't be necessary.

**Comment by DanAlbert** [comment]
Prefab doesn't package anything. Could you file an AGP bug?
