### ISSUE TITLE
not compatible library issue

### ISSUE THREAD

**Issue by DanAlbert** [google/prefab#155]
I encountered following logs when running `./gradew aR`:
```
> Task :app:configureCMakeRelWithDebInfo[x86_64]
C/C++: prefabcom.google.prefab.api.NoMatchingLibraryException: No compatible library found for //chinese-calendar/libchinese-calendar.so. Rejected the following libraries:
C/C++: prefabandroid.arm64-v8a: User is targeting x86_64 but library is for arm64-v8a
C/C++: prefabandroid.armeabi-v7a: User is targeting x86_64 but library is for armeabi-v7a
C/C++: prefabandroid.x86: User is targeting x86_64 but library is for x86
C/C++: prefabandroid.x86_64: User is using a static STL but library requires a shared STL
```

my `abi.json` as following:
```
{"api": 21,"abi": "x86_64","ndk": 21,"stl": "c++_shared","static":true}
```

I guess above logs are caused by `stl`,  am I correct?

the `lts` field's value can be one of `c++_shared|c++_static|gnustl_shared|gnustl_static|none|stlport_shared|stlport_static|system` , am I correct?

```
Usage: prefab [OPTIONS] PACKAGE_PATH...

  https://google.github.io/prefab/

Android specific configuration options:
  --abi TEXT                       Target ABI.
  --os-version TEXT                Target OS version.
  --stl [c++_shared|c++_static|gnustl_shared|gnustl_static|none|stlport_shared|stlport_static|system]
                                   STL used by the application.
  --ndk-version INT                Major version of the NDK used by the
                                   application.

Options:
  --build-system TEXT  Generate integration for the given build system.
  --output DIRECTORY   Output path for generated build system integration.
  --platform TEXT      Target platform. Only 'android' is currently supported.
  -h, --help           Show this message and exit
```

_Originally posted by @leleliu008 in https://github.com/google/prefab/issues/74#issuecomment-1115499272_

**Comment by DanAlbert** [comment]
> C/C++: prefabandroid.x86_64: User is using a static STL but library requires a shared STL

> "static":true

These two things are inconsistent. I'd need to see the build.gradle and the prefab package to tell you what happened. Closing for tracking reasons until I get that info, but will reopen when we get it.

**Comment by leleliu008** [comment]
`build.gradle.kts` is here: https://github.com/leleliu008/android-calendar-for-the-aged/blob/master/app/build.gradle.kts

the aar can be donwloaded from https://repo1.maven.org/maven2/com/fpliu/ndk/pkg/prefab/android/21/chinese-calendar/2022.04.22/chinese-calendar-2022.04.22.aar

**Comment by DanAlbert** [comment]
The actual abi.json does not match what you reported.

```bash
$ cat prefab/modules/libchinese-calendar.so/libs/android.x86_64/abi.json
{"api": 21,"abi": "x86_64","ndk": 21,"stl": "c++_shared","static":false}
```

The log message you're reading is about the shared library, and the abi.json is correct.

https://github.com/leleliu008/android-calendar-for-the-aged/blob/a1103eb6f3dc33c6856918cc9dcb59dd49b6b6cb/app/build.gradle.kts#L95-L100

The log is correct. These two configurations are not compatible. Your app is using c++_static (that's the default) which means it cannot have any shared library dependencies that use libc++. That's why it's not exposing the shared library to the build. It _is_ exposing the static library to the build, because that one is usable for the build configuration.

**Comment by leleliu008** [comment]
Thank you for your explanation. 

When I packed my prefab aar file, I refer to the https://mvnrepository.com/artifact/com.android.ndk.thirdparty , I find these `abi.json` all have `"stl": "c++_shared"`, even some of them are not compiled with `libc++_shared.so`, thus I thought `"stl": "c++_shared"` is fixed config.
