### ISSUE TITLE
Use prefab from build.gradle to publish a precompiled library.

### ISSUE THREAD

**Issue by ximo1234** [google/prefab#156]
**Describe the bug**

Hello.

I have an android library that has a precompiled dependency, I include it in CMakeLists.txt as follows:

```
add_library(externalLib SHARED IMPORTED)
set_target_properties(externalLib PROPERTIES IMPORTED_LOCATION
    ${PROJECT_FOLDER}/externalDependency/lib/${ANDROID_ABI}/libexternalLibrary.so
)

```

But later if in build.gradle I try to expose it in the aar using prefab like this:

```
buildFeatures.prefabPublishing true
prefab{
    externalLib{
        headers "externalDependency/include"
    }
}
```

I get an error:

`[CXX1404] did not find implicitly required targets: externalLib`

For CMake targets that define the code from where they are compiled if it works:

```
add_library(internalLib SHARED
    myInternalLibrary/src/internalLibrary.cpp)
```
    
```
buildFeatures.prefabPublishing true
prefab{
    internalLib{
        headers "src/main/cpp/myInternalLibrary/include"
    }
}
```

**To Reproduce**

1. Download code from [https://github.com/ximo1234/PrefabPrebuildLibrary](https://github.com/ximo1234/PrefabPrebuildLibrary)
2. Make sure it compiles
3. Remove comments from the file: mylib/build.gradle, line 43 and 47
4. Try to compile again, it fails

**Expected behavior**

I expected the precompiled library to be added to the .aar but it doesn't work.

**Environment:**
Prefab version: Don't know, the one that comes with Android Studio built on May 18, 2022

Host OS: Ubuntu 22.04
Target platform: Android
Target ABI: arm64-v8a  armeabi-v7a  x86  x86_64
Target OS version: API 32
Build system: clang

**Additional context**

I tried putting `GLOBAL` in the CMake `add_library` command but that didn't work either.

Can any changes be made to the CMakeLists.txt or build.gradle to expose this library in the .aar output?

Using command line prefab I sucess done what I want, but be cool that this can be done via build.gradle.

Thank you so much.

**Comment by DanAlbert** [comment]
You want the AGP bug tracker. Prefab doesn't create archives. https://issuetracker.google.com/173551290
