### ISSUE TITLE
[BUG] when used prefab, the module aar will have duplicate so. The one in the jni/lib, A another one is in the prefab dir.

### ISSUE THREAD

**Issue by popoaichuiniu** [google/prefab#163]
It causes problem when use aar contains  duplicate so :
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/15939275/206161915-25105b1f-543a-4cc8-a7c4-84b4e2746cd7.png">
1.  how can i fix it **except use pickFirst** (i am a android sdk developer, the app developer use my sdk is not pleasure to use this way) or  **exclude so in jni/lib and  only keep prefab dir so when pack my aar** (i am  uncertain that all versions AGP packed the so in the pfeab dir to apk. If not, our sdk can't work)?

**Comment by DanAlbert** [comment]
Not a prefab issue. https://issuetracker.google.com/214395989

**Comment by DanAlbert** [comment]
You can also use `packagingOptions.exclude` (iirc) to exclude the `jniLibs` copy.

Please don't use this bug tracker for AGP questions in the future. File AGP bugs so they know what a pain this is. Prefab cannot fix these problems so filing them here won't get anything fixed.
