### ISSUE TITLE
[FR] Support app module denpends on another module which all have C/C++ code.

### ISSUE THREAD

**Issue by peerless2012** [google/prefab#165]
**Is your feature request related to a problem? Please describe.**
I have many modules in an android studio project,  module-a is a base module whitch has C/C++ library, and other modules depend on module-a, and other modules also have C/C++ and thire build depend on module-a header files and link use libmodule-a.

**Describe the solution you'd like**
When module-a use prefab publish, other modules use prefab, the build will all finish.

**Additional context**
I need to run all modules once all, and publish them to maven center, and now both run and publish not work, because of can't find link so file.

**Comment by DanAlbert** [comment]
This sounds like you're asking for an AGP feature, not a prefab feature. Prefab already supports module and package dependencies. File a bug against AGP at http://b.android.com (the C++ component, I guess).

**Comment by peerless2012** [comment]
OK, I will create a issue on issue tracker.
