### ISSUE TITLE
[PKG] Oboe

### ISSUE THREAD

**Issue by sonicdebris** [google/prefab#27]
**Package name**
Oboe

**Package URL**
https://github.com/google/oboe

**Package source location**
https://github.com/google/oboe

**Comment by DanAlbert** [comment]
I'm guessing the Oboe folks will actually take this one themselves. @dturner FYI

**Comment by DanAlbert** [comment]
Done. `implementation "com.google.oboe:oboe:1.3.0"` in your build.gradle. Thanks a lot to @dturner for getting this done so quickly!
