### ISSUE TITLE
[PKG] libopus

### ISSUE THREAD

**Issue by Zingam** [google/prefab#44]
**Package name**
libopus

**Package URL**
http://www.opus-codec.org/

**Package source location**
https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz

**Comment by atkawa7** [comment]
@Zingam @artob @dani-garcia In the meantime there is feature that was created microsoft/vcpkg#10271. You can build the archive yourself. Its easy


```
export ANDROID_NDK_HOME="/Library/Android/sdk/ndk/<version>"
./vcpkg install opus  --triplet x86-android
./vcpkg install opus  --triplet x64-android
./vcpkg install opus  --triplet arm-android
./vcpkg install opus  --triplet arm64-android
./vcpkg export opus  --triplet x86-android --prefab
```

The resulting pom 

```xml
   <groupId>com.vcpkg.ndk.support</groupId>
    <artifactId>opus</artifactId>
    <version>1.3.1</version>
```

or Gradle 

```gradle
  implementation "com.vcpkg.ndk.support:opus:1.3.1"
```

**Comment by gamelaster** [comment]
@atkawa7 sadly, for me, this doesn't for, due libopus exports nothing :-(

**Comment by leleliu008** [comment]
This package had been publish to my maven repository hosted on github https://github.com/leleliu008/ndk-pkg-prefab-aar-maven-repo

You’re welcome to give it a try.

**Comment by isaacwein** [comment]
wow thank you so much I never used VCPKG it make building those c libraries so simple 

i needed opus for a pjsip android project even though pjsip is not supported in VCPKG but opus and openssl is suported with vcpkg and it made pjsip so much easier to compile

https://github.com/telebroad/pjsip-android-docker
