### ISSUE TITLE
[PKG] ffmpeg

### ISSUE THREAD

**Issue by Zingam** [google/prefab#46]
**Package name**
ffmpeg

**Package URL**
https://www.ffmpeg.org/

**Package source location**
https://www.ffmpeg.org/download.html#get-sources

**Comment by alexcohn** [comment]
See also https://github.com/tanersener/mobile-ffmpeg

**Comment by sonicdebris** [comment]
Considering that ffmpeg includes a collection of a lots of encoders and decoders, how should the need for possibly different configurations be addressed (if it can be addressed at all?)

I can already imagine that not everyone will want all the available video and audio codecs, some might need only audio codecs, some might need only codecs related to a certain type of application, most people will need to avoid GPL code altogether and so on.

Also, many of the recommended codecs actually rely on other libraries.

**Comment by DanAlbert** [comment]
The package could expose a handful of different configurations as separate libraries.

**Comment by alexcohn** [comment]
@sonicdebris look at the GitHub project that I linked above. It already exposes multiple variants that address the GPL vs. LGPL, external dependencies, and other issues that you do and that you don't mention. Currently, it produces AARs for Java developers. I am researching the ways to extend this approach to enable prefab as well.

**Comment by alexcohn** [comment]
So, I have two versions of ffmpeg libraries for Android, *min* and *full*, prepared for API=24 and API=16/21, altogether 4 AARs. The problem with this is that there can be *almost any combination* of  40+ external libraries linked into ffmpeg (including openh264, libxml2, or tesseract). I am afraid it's not feasible to maintain even most important sets of external libraries.

**Comment by alexcohn** [comment]
@DanAlbert there is another problem with this library (and maybe some others). Parts of the base **ffmpeg** and its *external* libraries may have legitimate licenses to be distributed as source code, but be subject to MPEG LA restrictions when distribution of binaries is involved. The language of MPEG LA license terms is deliberately vague and can be interpreted such that the distributors of a prefabbed version of the library may be required to pay $0.20 per download even if they make 0 money on that.

**Comment by DanAlbert** [comment]
It's sounding like maybe ffmpeg is better off distributed as source. Anyone think there's a good argument for distributing some subset of it as binaries?

**Comment by alexcohn** [comment]
Building of **ffmpeg** from source with the correct list of extra libraries and parameters, is a well-known hassle. The problem is, choosing the correct list of extra libraries and parameters cannot be solved by **Prefab**, hence distributing it as binary you don't gain much.

**Comment by bvitaliyg** [comment]
There're a lot of cases when you only need minimum/default/full packages. Building FFmpeg from scratch can be very painful especially for someone who haven't done this before and just need some default codecs. I think at least these 3 versions should be provided. Additionally, packages with popular external libraries (e.g. h264) can be shared as well.

**Comment by alexcohn** [comment]
If you ask me, I would recommend Google to endorse the [FFmpegKit](https://github.com/tanersener/ffmpeg-kit) project, and sponsor the maintainer to add Prefab wrapper to the binaries of this project.

**Comment by leleliu008** [comment]
build from source is relatively easy for most people via [ndk-pkg](https://github.com/leleliu008/ndk-pkg)

build with `--disable-libfdk-aac`, the binary is distributable.

I have built it succesully with following dependencies:

![ffmpeg-dependencies](https://github.com/google/prefab/assets/3040852/85102657-59e2-4aed-8ccb-dcc9a62b780b)

Due to the file size is very large, I published it to GitHub Releases as Maven Local Repository bundle: https://github.com/leleliu008/ndk-pkg-prefab-aar-maven-repo/releases, anyone who want to use it, just download it and uncompress it to your Maven Local Repository.

I also wrote a example: https://github.com/leleliu008/ndk-pkg-prefab-example-ffmpeg
