### ISSUE TITLE
[PKG]libpng

### ISSUE THREAD

**Issue by ChristianRomberg** [google/prefab#51]
**Package name**
libpng

**Package URL**
http://www.libpng.org/pub/png/libpng.html

**Package source location**
https://sourceforge.net/projects/libpng/files/ (packages)
git://git.code.sf.net/p/libpng/code (direct git link)
https://sourceforge.net/p/libpng/code/ci/libpng16/tree/ (git browse)

**Comment by atkawa7** [comment]
@ChristianRomberg In the meantime there is feature that was created microsoft/vcpkg#10271. You can build the archive yourself. Its easy

```
export ANDROID_NDK_HOME="/Library/Android/sdk/ndk/<version>"
./vcpkg install libpng  --triplet x86-android
./vcpkg install libpng  --triplet x64-android
./vcpkg install libpng  --triplet arm-android
./vcpkg install libpng  --triplet arm64-android
./vcpkg export libpng  --triplet x86-android --prefab
```


In app/build.gradle

	com.vcpkg.ndk.support:libpng:1.6.37-6

And cmake flags

    externalNativeBuild {
                cmake {
                    arguments '-DANDROID_STL=c++_shared'
                    cppFlags "-std=c++17"
                }
            }

In gradle.properties

    android.enablePrefab=true
    android.enableParallelJsonGen=false
    android.prefabVersion=${prefab.version}

**Comment by leleliu008** [comment]
The vcpkg export as aar had broken for at least half a year.

This package had been publish to my maven repository hosted on github https://github.com/leleliu008/ndk-pkg-prefab-aar-maven-repo

You’re welcome to give it a try.
