### ISSUE TITLE
[PKG] libphonenumber

### ISSUE THREAD

**Issue by DanAlbert** [google/prefab#55]
Capturing request from https://github.com/android/ndk/issues/456#issuecomment-315532942

**Package name**
libphonenumber

**Package URL**
https://github.com/google/libphonenumber

**Package source location**
https://github.com/google/libphonenumber

**Comment by leleliu008** [comment]
This package had been publish to my maven repository hosted on github https://github.com/leleliu008/ndk-pkg-prefab-aar-maven-repo

You’re welcome to give it a try.
