### ISSUE TITLE
[DOC] Docs refer to CLI executable name `prefab`, but actual name is `cli`

### ISSUE THREAD

**Issue by dturner** [google/prefab#60]
**URL**
https://google.github.io/prefab/#usage

**Problem**
The documentation refers to an executable called `prefab`, however, after running `gradlew installDist` the binary which gets created is called `cli`. Additionally the output from `cli` is: 

    Usage: prefab [OPTIONS] [PACKAGE_PATH]...  

Suggest either updating docs or renaming CLI executable to `prefab`

**Comment by DanAlbert** [comment]
I'd prefer fixing the name, so recategorizing. Something worth doing before 1.0 is finalized.
