### ISSUE TITLE
[BUG] Prefab errors are not surfaced to Android Studio build log

### ISSUE THREAD

**Issue by dturner** [google/prefab#64]
**Describe the bug**
If prefab encounters an error during a build it is not surfaced to the user in the Android Studio build log.

**To Reproduce**
- Clone the curl-ssl repo
- Open app/build.gradle and comment out the following line: 
    `arguments "-DANDROID_STL=c++_shared"`
- Run gradle sync

**Expected behavior**
Build fails with a clear description of why it failed

**Actual behavior**
Build fails with the following message: 

    executing external native build for cmake /Users/donturner/Code/workspace-android/ndk-samples/prefab/curl-ssl/app/src/main/cpp/CMakeLists.txt
    Affected Modules: app

**Environment:**
Prefab version: (if not using the latest, please try the latest first) 

Host OS:
- [ ] Linux
- [ x] macOS
- [ ] Windows

Target platform:
Target ABI:
Target OS version:
Build system:

**Additional context**
It is possible to view the prefab output by opening the gradle tab then executing the curl-ssl > Tasks > build > build task. Not particularly easy to find.

**Comment by DanAlbert** [comment]
Refiled against AGP: https://issuetracker.google.com/150233489. Prefab is emitting the errors, AGP (or Studio) is just hiding them.
