### ISSUE TITLE
[PKG] PJSIP

### ISSUE THREAD

**Issue by dani-garcia** [google/prefab#68]
**Package name**
PJSIP

**Package URL**
https://www.pjsip.org

**Package source location**
https://github.com/pjsip/pjproject/archive/2.10.tar.gz

**Comment by leleliu008** [comment]
This package had been publish to my maven repository hosted on github https://github.com/leleliu008/ndk-pkg-prefab-aar-maven-repo

You’re welcome to give it a try.
