### ISSUE TITLE
[DOC] Example on Supporting Custom Archives on Local

### ISSUE THREAD

**Issue by atkawa7** [google/prefab#81]
Hi @DanAlbert . Thank you for such a great library. Just wondering is there an example on how to use a custom build aar file. I have creating my own aar file in the same manner as this project. However when I import the library in android it fails. 

```
.m2/repository/com/vcpkg/ndk/support/jsoncpp/1.9.2/jsoncpp-1.9.2.pom
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.vcpkg.ndk.support</groupId>
    <artifactId>jsoncpp</artifactId>
    <version>1.9.2</version>
    <packaging>aar</packaging>
    <description>The Vcpkg AAR for jsoncpp</description>
    <url>https://github.com/microsoft/vcpkg.git</url>

    <dependencies>
    </dependencies>
</project>
```
The following is the file renamed to zip to allow uploading to GitHub
[jsoncpp-1.9.2.zip](https://github.com/google/prefab/files/4272333/jsoncpp-1.9.2.zip)

**Comment by DanAlbert** [comment]
> However when I import the library in android it fails.

What's the failure? At a glance everything in the AAR checks out, but the error should make it more clear where I should be looking.

**Comment by atkawa7** [comment]
Thanks @DanAlbert I am closing this. The issue was related to empty strings for library names. And null export library. But its now all good. I have created a sample project here and it seems to be working now https://github.com/atkawa7/prefab-vpkg-integration-sample
