### ISSUE TITLE
[FR] per-platform includes?

### ISSUE THREAD

**Issue by DanAlbert** [google/prefab#9]
We don't currently support libraries that need to expose different headers for each platform or subplatform. Adding an optional `include` directory inside the library directory might be helpful for some libraries. I haven't encountered any yet, but it's possible.

**Comment by DanAlbert** [comment]
@enh-google do you remember encountering anything that would need this when you were first looking into ndkports? Wondering if I should make sure this is in 1.0 or not.

**Comment by enh-google** [comment]
no, i don't.
