### ISSUE TITLE
[PKG] The Google cpu_features library

### ISSUE THREAD

**Issue by alexcohn** [google/prefab#93]
**Package name**
The Google cpu_features library

**Package URL**
https://developer.android.com/ndk/guides/cpu-features

**Package source location**
https://github.com/google/cpu_features

**Comment by znakeeye** [comment]
No news regarding this? A prefab for `cpu_features` would certainly be useful!

**Comment by znakeeye** [comment]
I'm currently trying to integrate `cpu_features` in [ORX: Portable Game Engine](https://github.com/orx). Since we want to depend solely on light-weight `ndk-build`, building this library is not a no-brainer.

How hard would it be to create a **prefab** for `cpu_features`? It would certainly simplify matters a lot!

@alexcohn, @DanAlbert Any chance you could look into this?

PS. You could also consider adding an `Android.mk` for the "drop-in replacement of cpufeatures".

**Comment by DanAlbert** [comment]
> How hard would it be to create a prefab for cpu_features? It would certainly simplify matters a lot!

Most things are pretty easy with https://android.googlesource.com/platform/tools/ndkports/. You could probably do it in an afternoon.

> @DanAlbert Any chance you could look into this?

We don't have any bandwidth for expanding to new packages ourselves. We need to spend some significant time reducing the cost of the things we already do "maintain" (you'll notice that everything we currently have is still released as a beta, that's because we can't currently afford to keep up with releases, we need to build automation before we can consider making those non-beta, let alone expanding).

> PS. You could also consider adding an Android.mk for the "drop-in replacement of cpufeatures".

You'd need to file a bug against that project. We don't own that.

**Comment by leleliu008** [comment]
This package had been published to GitHub-Hosted Maven Repository: https://github.com/leleliu008/ndk-pkg-prefab-aar-maven-repo

You’re welcome to give it a try.

It was built with `android-21` API level.

It provides `arm64-v8a` `armeabi-v7a` `x86_64` `x86` four abis.

It includes both static and shared libraries.

If it doesn't meet your needs, you could try to mannully build it with [ndk-pkg](https://github.com/leleliu008/ndk-pkg),  you could use it via GitHub Actions https://github.com/leleliu008/ndk-pkg-package-manually-build

||                                                                                                                                                      
|-|                                                                                                                                                     
|<img src="https://github.com/google/prefab/assets/3040852/cca6c6cf-925d-4b48-9c04-c88e7b36567a" width="311px" >|

**Comment by znakeeye** [comment]
Great indeed, but `Google` should really add this one to their list of supported prefab packages...

And what about different NDK versions? If you target e.g. v23, will it work without any weird bugs/crashes? 🤔

**Comment by leleliu008** [comment]
[ndk-pkg](https://github.com/leleliu008/ndk-pkg) downloads a proper version of NDK for you, althougth you can pass `--ndk-home=<ANDROID-NDK-HOME>` option to tell your pre-installed NDK location, but it is discourage. If you use it with GitHub Actions, no need to care about that.

There are almost 600 packages tested in my CI (GitHub Actions) https://github.com/leleliu008/ndk-pkg-formula-repository-offical-core

I can't say there is no any problems, I myself use it everyday though, use at your own risk.

That's the risk you take if you use any open-source software.

I used to want to use [vcpkg](https://github.com/microsoft/vcpkg). It claimed that it supports exporting android prefab aars, but it has broken for at least harf a year. It powerd by Microsoft, a very big company, there are many many people work for it, but why a small broken feature can't be fixed? I don't known, but it indeed happeded. God knows exactly when it will be fixed, maybe never!

**Comment by znakeeye** [comment]
@DanAlbert Completed? 🤔

**Comment by DanAlbert** [comment]
https://github.com/google/prefab/issues/93#issuecomment-1678343389

**Comment by znakeeye** [comment]
It's not documented in the Android docs, hence not supported? In my book, at least.

Is a GitHub hosted Maven the way forward?

**Comment by DanAlbert** [comment]
> It's not documented in the Android docs, hence not supported? In my book, at least.

It's not practical for Android to document every community provided library (nor does anyone expect that of any other platform afaik). In this particular case it's a community provided prebuilt of a Google-written library, so the cpu_features should maybe point people there (or better yet, host it themselves), but if that's what you mean you'll need to file a bug for that project.

> Is a GitHub hosted Maven the way forward?

We don't care at all where packages are hosted. That was an explicit design goal. Whatever is easiest for the community is the best choice.

**Comment by leleliu008** [comment]
As a open-source software developer, GitHub is a good place to host these artifacts.

Actually, I published a lot of aars to `Maven Central Prepository` last year, you could find them here https://central.sonatype.com/namespace/com.fpliu.ndk.pkg.prefab.android.21 , unfortunately, some so files has problem as described in https://github.com/android/ndk/issues/1865, I fixed the bug this year.

Once published to `Maven Central Prepository`, I'm not able to remove/update/modify that artifact, so, this time I decide to use GitHub to host these artifacts. I will write more test cases to ensure these artifacts are ok. and I will republish these artifacts to `Maven Central Prepository` at some point.
