### ISSUE TITLE
[FR] Update OpenSSL to latest version

### ISSUE THREAD

**Issue by akoeplinger** [google/prefab#95]
Right now the latest version of OpenSSL on https://maven.google.com is 1.1.1.d while https://www.openssl.org/ published 1.1.1e and 1.1.1f in the meantime.

Do you plan on updating OpenSSL and other libraries regularly once you're out of the alpha stage? 

I'm also curious what your thoughts are around responding to security issues in libraries.

**Comment by DanAlbert** [comment]
There's a big item on my to-do list to take some auto-updating tools that @hhb wrote for handling these sorts of things in AOSP and putting them to use here. Not having had the time to do that is a lot of the reason for the alpha labels.

I can get an update out for this fairly trivially though, so thanks for the nudge!

**Comment by DanAlbert** [comment]
Uploaded https://android-review.googlesource.com/c/platform/tools/ndkports/+/1282033 to update each of them (json-cpp has no updates). Still need to check the NDK sample to make sure it's not horribly broken though :)

**Comment by DanAlbert** [comment]
Basically ready to ship, but our maven tooling was recently migrated so I'm waiting on some approvals before I can actually click the publish button. Should be up tomorrow.

**Comment by DanAlbert** [comment]
Done now. Sorry for the delay!

**Comment by akoeplinger** [comment]
Thank you!

**Comment by akoeplinger** [comment]
@DanAlbert OpenSSL just published 1.1.1g which includes a "Severity: High" security fix for https://www.openssl.org/news/secadv/20200421.txt.

**Comment by DanAlbert** [comment]
Thanks for the heads up. Starting an update.

**Comment by DanAlbert** [comment]
Live now. Will get the NDK sample updated to match shortly.
