### ISSUE TITLE
[FR] nice to have: the cli to accept AAR file

### ISSUE THREAD

**Issue by alexcohn** [google/prefab#96]
**Describe the solution you'd like**
I believe that most work is done with AAR packages. It would be nice if **prefab** command could transparently work with such archives, not expecting the user to extract the AAR manually.

**Describe alternatives you've considered**
I am afraid that manual extraction of the AAR may cause or hide some problems with some packages.

**Comment by DanAlbert** [comment]
What's the use case for this? Gradle handles AAR extraction. There are a lot of other things that Gradle has to do for the AAR that I'd be worried about doing manually beyond unzip.

**Comment by alexcohn** [comment]
The simple use case is to drop in an AAR with prefab and check whether it is correct. That's how I have been finding glitches in my research of prefab creation.

**Comment by alexcohn** [comment]
On the second thought, as you insist that Prefab never deals with the AAR in closed form, and depends totally on the way AGP handles the AAR for it, and may use other bundle formats instead of AAR, this feature may be less attractive.

**Comment by DanAlbert** [comment]
My thinking on this one is mostly that an AAR alone requires a bit more work. Dependency resolution and such play a big part, so I'm wondering if they're useful outside a build system that already knows how to deal with maven dependencies.

Until we actually have a non-Android (or at least non-Gradle) consumer of these, it's hard to predict what form that will take, so it's not something I want to start building for until we have a better idea of that.

For your use case, test the prefab package before it's zipped into the AAR? Testing an AAR is something that should be done in gradle. That's able to test more completely and automatically anyway.

**Comment by alexcohn** [comment]
Agreed.
