### ISSUE TITLE
[PKG] cpprestsdk

### ISSUE THREAD

**Issue by dmn-star** [google/prefab#99]
**Package name**
cpprestsdk

**Package URL**
https://github.com/microsoft/cpprestsdk

**Package source location**
https://github.com/microsoft/cpprestsdk

**Comment by leleliu008** [comment]
This package had been publish to my maven repository hosted on github https://github.com/leleliu008/ndk-pkg-prefab-aar-maven-repo

You’re welcome to give it a try.
